// Generated by gencpp from file test1/client_info.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_CLIENT_INFO_H
#define TEST1_MESSAGE_CLIENT_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test1
{
template <class ContainerAllocator>
struct client_info_
{
  typedef client_info_<ContainerAllocator> Type;

  client_info_()
    : client_serial(0)  {
    }
  client_info_(const ContainerAllocator& _alloc)
    : client_serial(0)  {
  (void)_alloc;
    }



   typedef uint32_t _client_serial_type;
  _client_serial_type client_serial;




  typedef boost::shared_ptr< ::test1::client_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test1::client_info_<ContainerAllocator> const> ConstPtr;

}; // struct client_info_

typedef ::test1::client_info_<std::allocator<void> > client_info;

typedef boost::shared_ptr< ::test1::client_info > client_infoPtr;
typedef boost::shared_ptr< ::test1::client_info const> client_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test1::client_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test1::client_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test1': ['/home/zyvv/work/Rosprj/catkin/src/test1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test1::client_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test1::client_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::client_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::client_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::client_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::client_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test1::client_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67bbc1d16de51fe473a2b7db355db7a0";
  }

  static const char* value(const ::test1::client_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67bbc1d16de51fe4ULL;
  static const uint64_t static_value2 = 0x73a2b7db355db7a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::test1::client_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test1/client_info";
  }

  static const char* value(const ::test1::client_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test1::client_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 client_serial\n\
";
  }

  static const char* value(const ::test1::client_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test1::client_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.client_serial);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct client_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test1::client_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test1::client_info_<ContainerAllocator>& v)
  {
    s << indent << "client_serial: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.client_serial);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST1_MESSAGE_CLIENT_INFO_H
