// Generated by gencpp from file test1/robot_info.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_ROBOT_INFO_H
#define TEST1_MESSAGE_ROBOT_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test1
{
template <class ContainerAllocator>
struct robot_info_
{
  typedef robot_info_<ContainerAllocator> Type;

  robot_info_()
    : Robot_Serial(0)
    , Control_State(0)
    , Robot_State(0)
    , Robot_Position(0)
    , Task_Type(0)
    , Route_Serial(0)  {
    }
  robot_info_(const ContainerAllocator& _alloc)
    : Robot_Serial(0)
    , Control_State(0)
    , Robot_State(0)
    , Robot_Position(0)
    , Task_Type(0)
    , Route_Serial(0)  {
  (void)_alloc;
    }



   typedef uint16_t _Robot_Serial_type;
  _Robot_Serial_type Robot_Serial;

   typedef uint16_t _Control_State_type;
  _Control_State_type Control_State;

   typedef uint16_t _Robot_State_type;
  _Robot_State_type Robot_State;

   typedef uint16_t _Robot_Position_type;
  _Robot_Position_type Robot_Position;

   typedef uint16_t _Task_Type_type;
  _Task_Type_type Task_Type;

   typedef uint16_t _Route_Serial_type;
  _Route_Serial_type Route_Serial;




  typedef boost::shared_ptr< ::test1::robot_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test1::robot_info_<ContainerAllocator> const> ConstPtr;

}; // struct robot_info_

typedef ::test1::robot_info_<std::allocator<void> > robot_info;

typedef boost::shared_ptr< ::test1::robot_info > robot_infoPtr;
typedef boost::shared_ptr< ::test1::robot_info const> robot_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test1::robot_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test1::robot_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test1': ['/home/zyvv/work/Rosprj/catkin/src/test1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test1::robot_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test1::robot_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::robot_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::robot_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::robot_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::robot_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test1::robot_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7468c010c81fc0248bb003b9877aa15";
  }

  static const char* value(const ::test1::robot_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7468c010c81fc02ULL;
  static const uint64_t static_value2 = 0x48bb003b9877aa15ULL;
};

template<class ContainerAllocator>
struct DataType< ::test1::robot_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test1/robot_info";
  }

  static const char* value(const ::test1::robot_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test1::robot_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 Robot_Serial\n\
uint16 Control_State\n\
uint16 Robot_State\n\
uint16 Robot_Position\n\
uint16 Task_Type\n\
uint16 Route_Serial\n\
";
  }

  static const char* value(const ::test1::robot_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test1::robot_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Robot_Serial);
      stream.next(m.Control_State);
      stream.next(m.Robot_State);
      stream.next(m.Robot_Position);
      stream.next(m.Task_Type);
      stream.next(m.Route_Serial);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test1::robot_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test1::robot_info_<ContainerAllocator>& v)
  {
    s << indent << "Robot_Serial: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Robot_Serial);
    s << indent << "Control_State: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Control_State);
    s << indent << "Robot_State: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Robot_State);
    s << indent << "Robot_Position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Robot_Position);
    s << indent << "Task_Type: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Task_Type);
    s << indent << "Route_Serial: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Route_Serial);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST1_MESSAGE_ROBOT_INFO_H
