// Generated by gencpp from file test1/server.msg
// DO NOT EDIT!


#ifndef TEST1_MESSAGE_SERVER_H
#define TEST1_MESSAGE_SERVER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test1
{
template <class ContainerAllocator>
struct server_
{
  typedef server_<ContainerAllocator> Type;

  server_()
    : IsStart(0)  {
    }
  server_(const ContainerAllocator& _alloc)
    : IsStart(0)  {
  (void)_alloc;
    }



   typedef uint8_t _IsStart_type;
  _IsStart_type IsStart;




  typedef boost::shared_ptr< ::test1::server_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test1::server_<ContainerAllocator> const> ConstPtr;

}; // struct server_

typedef ::test1::server_<std::allocator<void> > server;

typedef boost::shared_ptr< ::test1::server > serverPtr;
typedef boost::shared_ptr< ::test1::server const> serverConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test1::server_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test1::server_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test1': ['/home/zyvv/work/Rosprj/catkin/src/test1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test1::server_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test1::server_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::server_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test1::server_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::server_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test1::server_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test1::server_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f943cc528f6d0372715159c657f91c2e";
  }

  static const char* value(const ::test1::server_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf943cc528f6d0372ULL;
  static const uint64_t static_value2 = 0x715159c657f91c2eULL;
};

template<class ContainerAllocator>
struct DataType< ::test1::server_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test1/server";
  }

  static const char* value(const ::test1::server_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test1::server_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 IsStart\n\
";
  }

  static const char* value(const ::test1::server_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test1::server_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.IsStart);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct server_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test1::server_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test1::server_<ContainerAllocator>& v)
  {
    s << indent << "IsStart: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.IsStart);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST1_MESSAGE_SERVER_H
