set(_CATKIN_CURRENT_PACKAGE "test1")
set(test1_VERSION "0.1.0")
set(test1_MAINTAINER "zyvv <zyvv@todo.todo>")
set(test1_PACKAGE_FORMAT "1")
set(test1_BUILD_DEPENDS "roscpp")
set(test1_BUILD_EXPORT_DEPENDS "roscpp")
set(test1_BUILDTOOL_DEPENDS "catkin")
set(test1_BUILDTOOL_EXPORT_DEPENDS )
set(test1_EXEC_DEPENDS "roscpp")
set(test1_RUN_DEPENDS "roscpp")
set(test1_TEST_DEPENDS )
set(test1_DOC_DEPENDS )
set(test1_DEPRECATED "")